### ISSUE TITLE
Allow programmatic execution without importing aspen.__main__

### ISSUE THREAD

**Issue by jaraco** [gratipay/aspen.py#540]
Logging should be implicitly configured or available to be explicitly configured, per [this comment](https://github.com/gratipay/aspen.py/commit/a1df2bae9293d2f1f40e05a17d7de699638e18c0#commitcomment-15565648).

**Comment by pjz** [comment]
Okay, upon looking at this again, the current code is correct because: `init_logging` initializes handlers and formats and such, which _a module should NOT do_.  This is why it's done in `__main__`.  

Logging _input_ is (or should be) done with the usual 

    log = logging.getLogger(__name__)
    log.debug(...)

 in each module.  The *output* should be configured by whatever app is using the aspen module.  In the `python -m aspen` case, that's `__main__` which is why that's configured there.  In other cases (where aspen is used via WSGI, for instance), that set of logging configuration should be left to the calling app.

**Comment by jaraco** [comment]
But what if what I want to do is invoke aspen, just as `python -m aspen` does, except I need to perform some actions first. This is [exactly the need](https://github.com/whit537/mongs/blob/master/launch.py) in mongs. The referenced commit, by taking logging configuration out of the server initialization, will cause Mongs not to log anything (because logging hasn't been configured). There should be a way for Mongs to say, "Aspen, please configure logging output as you normally would".

**Comment by jaraco** [comment]
And without accepting this pull request, Mongs cannot do that except to `import aspen.__main__`, which is awkward, at best.

**Comment by pjz** [comment]
...or to just copy the code from aspen.__main__, which is what it's mostly there for: to serve as an example.

**Comment by jaraco** [comment]
So are you suggesting that the changelog for this next release will read something like:

> Aspen no longer configures logging output during server setup. Instead, if your app requires configuration of logging, it should do that configuration itself. If you wish for the configuration to be the same as what Aspen normally outputs, your app should copy the 20 lines or so from `aspen.__main__` into the startup routine for your app.

It strikes me as awkward that we would ask an app to copy code from aspen, especially when it's more than one or two lines, when it's trivially easy to expose that functionality to avoid the duplication (and unintended divergence).

Don't get me wrong. Using the logging framework is an excellent improvement. And giving the applications the ability to customize how output is managed is fantastic.

Would you accept a pull request that adds a comment directing users to copy that code into their projects?

**Comment by whit537** [comment]
/me picks up the convo in https://github.com/gratipay/aspen.py/pull/541 ...

**Comment by whit537** [comment]
> This is [exactly the need](https://github.com/whit537/mongs/blob/master/launch.py) in mongs.

[permalink](https://github.com/whit537/mongs/blob/0f59e965bc877fd2acb7aa4da757189bdd56cc1a/launch.py)

**Comment by whit537** [comment]
Dialing back out here since we have an alternative PR in #545 ...

**Comment by whit537** [comment]
@jaraco Let's discuss this in terms of the roadmap for Aspen (#357). The tl;dr is that we're giving up on being a full-featured web framework, in light of the ascendency of Django and Flask (#526). Instead, we're going to provide dispatch and simplates as a plugin for Django and Flask, utilizing the request and response objects, etc., from those frameworks. We plan to ship a very basic framework using `environ` and `start_response` instead of Request and Response objects.

The implication for Mongs is that we'll need to decide what framework combo we want to use in the future: https://github.com/whit537/mongs/issues/29.

> especially when it's more than one or two lines

The implication for this ticket is that we *should* be trying to get `__main__.py` down to one or two lines. Skimming #527, I'm not sure we even log anything anymore on startup, which means we can cut out the logging config entirely, for example.

**Comment by jaraco** [comment]
Fine by me. I withdraw the PR.

**Comment by whit537** [comment]
!m @jaraco
